support for redisqlite with python
nimbella/nimbella-sdk-python pull request #10
Opened 2021-05-23 05:35 UTC by sciabarracom

this pm implements in pythonic way the redisqlite API

2021-05-24 08:01 UTC, rabbah commented
The programming interface the sdk exposes for MySQL vs sql lite is supposed to be the same? That is if I change the client can I use the sql methods between the sql implementations interchangeably?

2021-05-24 12:02 UTC, sciabarracom commented
The api "esql" (I renamed it on purpose) can be adapted easily to work with mysql, postgresl, oracle and everything but the underlying sql would be different so it is not so easy to make it portable. More or less like JDBC, same API but the code does not work from Oracle to Postgresql

2021-05-25 08:42 UTC, jthomas requested changes
I'm not the best Python person but looks good to me apart from the doc change.

2021-05-25 08:42 UTC, jthomas commented on README.md
> +#### Embedded SQL support
Can we move this content to "docs" and have a short section here like we did in the Node.js example?

2021-07-13 14:57 UTC, jthomas commented
Any comments @rabbah before I merge? Speak now or forever hold your peace...

2021-07-13 14:59 UTC, rabbah commented
Are the APIs on par between python and node? That is are we providing the same SDK?

2021-07-13 15:28 UTC, sciabarracom commented
Yes the API are the same in nodejs and python

2021-07-14 22:53 UTC, rabbah commented
👍

2021-07-15 10:44 UTC, jthomas approved these changes

2021-07-15 10:45 UTC, merged